[build]
target-dir = "target"

[target.aarch64-unknown-optee]
ar = "aarch64-linux-gnu-ar"
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu]
ar = "aarch64-linux-gnu-ar"
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-C", "link-arg=-fuse-ld=bfd"]