[package]
name = "airaccout-ta-basic"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core TEE dependencies - following eth_wallet pattern
optee-utee-sys = { path = "../../third_party/incubator-teaclave-trustzone-sdk/optee-utee/optee-utee-sys" }
optee-utee = { path = "../../third_party/incubator-teaclave-trustzone-sdk/optee-utee" }

# Serialization - same as eth_wallet
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }

# UUID handling
uuid = { version = "1.8", default-features = false }

# Error handling
anyhow = "1.0"

[build-dependencies]
uuid = { version = "1.8", default-features = false }
optee-utee-build = { path = "../../third_party/incubator-teaclave-trustzone-sdk/optee-utee-build" }

[profile.release]
lto = false
opt-level = 3