[package]
name = "airaccount-basic-ca"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "airaccount-basic-ca"
path = "src/main.rs"

[dependencies]
optee-teec = { path = "../../../third_party/incubator-teaclave-trustzone-sdk/optee-teec" }
uuid = { version = "1.0", features = ["v4", "serde"] }
hex = "0.4"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }