[package]
name = "airaccount-ca"
version = "0.1.0"
edition = "2021"
authors = ["AirAccount Team"]
description = "AirAccount Client Application for communicating with TEE"
license = "MIT"

[dependencies]
# OP-TEE Client SDK (conditional)
optee-teec = { path = "../../third_party/incubator-teaclave-trustzone-sdk/optee-teec", optional = true }

# Protocol definitions
airaccount-proto = { path = "../proto" }

# CLI framework
clap = { version = "4.0", features = ["derive"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Async runtime
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "macros"] }

# UUID handling
uuid = { version = "1.8", features = ["v4", "serde"] }

# Error handling
anyhow = "1.0"

# Logging
env_logger = "0.10"
log = "0.4"

# Hex encoding/decoding
hex = "0.4"

# Features
[features]
default = ["mock_tee"]
mock_tee = []
real_tee = ["optee-teec"]

[[bin]]
name = "airaccount-ca"
path = "src/main.rs"