[package]
name = "airaccount-ta"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = { path = "../../third_party/incubator-teaclave-trustzone-sdk/rust/libc" }
optee-utee-sys = { path = "../../third_party/incubator-teaclave-trustzone-sdk/optee-utee/optee-utee-sys" }
optee-utee = { path = "../../third_party/incubator-teaclave-trustzone-sdk/optee-utee" }
secure_db = { path = "../../third_party/incubator-teaclave-trustzone-sdk/crates/secure_db" }

# 生产级安全依赖
uuid = { version = "1.8", default-features = false }
anyhow = "1.0"
hex = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"

[build-dependencies]
uuid = { version = "1.8", default-features = false }
optee-utee-build = { path = "../../third_party/incubator-teaclave-trustzone-sdk/optee-utee-build" }

[profile.release]
lto = false
opt-level = 3