[package]
name = "airaccout-mock-hello"
version = "0.1.0"
edition = "2021"

[dependencies]
# Serialization - same as eth_wallet pattern
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }

# UUID handling
uuid = { version = "1.8", features = ["v4", "serde"] }

# Error handling
anyhow = "1.0"

# Command line interface
clap = { version = "4.0", features = ["derive"] }

# Tokio for async simulation
tokio = { version = "1.0", features = ["full"] }

# For timestamps
chrono = { version = "0.4", features = ["serde"] }

[[bin]]
name = "mock-ta"
path = "src/bin/mock_ta.rs"

[[bin]]
name = "mock-ca"
path = "src/bin/mock_ca.rs"