[package]
name = "airaccount-ca"
version = "0.1.0"
edition = "2021"

[dependencies]
optee-teec = { path = "../../third_party/incubator-teaclave-trustzone-sdk/optee-teec" }
uuid = { version = "1.8", features = ["v4", "serde"] }
anyhow = "1.0"
hex = "0.4"
clap = { version = "4.0", features = ["derive"] }

[build-dependencies]
anyhow = "1.0"