// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/**
 * AirAccount KMS — TEE remote-attestation verifier (issue #37, MVP / Phase 1).
 *
 * Verifies the evidence produced by `GET /attestation?nonce=<hex>`:
 *   1. the echoed nonce equals the one we sent (binds this exchange),
 *   2. the RSA-PSS signature over SHA256(nonce | ta_measurement) is valid
 *      under the attestation public key,
 *   3. `ta_measurement` matches a known-good reference value, and
 *   4. the attestation public key fingerprint matches a pinned value (TOFU).
 *
 * ⚠️ TRUST-ROOT SCOPE — READ THIS.
 * The OP-TEE attestation key is *self-generated by the device* and has NO
 * certificate chain to an NXP root (confirmed against `core/pta/attestation.c`
 * and RM00284 — see `docs/design/37-remote-attestation-design.md` R-1). So this
 * verifier proves "the evidence was produced by a real OP-TEE running this exact
 * TA build", but it does NOT prove "this is a genuine NXP part the verifier never
 * trusted before". The attestation key must be trusted out-of-band: pin it on
 * first use (TOFU) or fetch it from a published, signed reference. Anchoring to
 * an NXP root is Phase 2 (ELE), still gated on R-1. Do not market TOFU as a
 * decentralisation win — it is a security compromise (design doc §9).
 */

import { createHash, createPublicKey, verify as cryptoVerify, constants } from "node:crypto";

/** Raw evidence as returned by `GET /attestation` (all binary fields hex). */
export interface AttestationEvidence {
  schema: string;
  nonce: string;
  ta_uuid: string;
  ta_measurement: string;
  signature: string;
  attest_pubkey_exp: string;
  attest_pubkey_mod: string;
  /** TEE_ALG_* id; 0x70414930 = RSASSA_PKCS1_PSS_MGF1_SHA256. */
  sig_alg: number;
  ree_time_secs: number;
  trust_root?: string;
}

export interface VerifyOptions {
  /** The exact nonce (hex) the caller sent in the request. Required. */
  expectedNonceHex: string;
  /**
   * Allow-list of known-good TA measurements (hex, 32-byte SHA-256 of the TA
   * signed header). Distributed per design doc §7.1. Supports multiple values
   * for rolling upgrades. If omitted, the measurement check is SKIPPED and a
   * warning is returned — do not do this in production.
   */
  expectedMeasurementsHex?: string[];
  /**
   * Pinned attestation-key fingerprints (hex SHA-256 of the modulus). TOFU
   * trust root. If omitted, the fingerprint is returned for first-use pinning
   * and a warning is emitted — do not skip pinning in production.
   */
  pinnedKeyFingerprintsHex?: string[];
}

export interface VerifyResult {
  ok: boolean;
  /** Human-readable reasons every failed check produced (empty when ok). */
  errors: string[];
  /** Non-fatal advisories (e.g. skipped optional checks). */
  warnings: string[];
  /** SHA-256 of the attestation key modulus (hex) — use this to pin (TOFU). */
  keyFingerprintHex: string;
  /** The verified TA measurement (hex) on success. */
  measurementHex: string;
  /** True iff the RSA-PSS signature itself verified. */
  signatureValid: boolean;
}

const TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA256 = 0x70414930;

function hexToBuf(hex: string, field: string): Buffer {
  const clean = hex.trim();
  if (clean.length === 0 || clean.length % 2 !== 0 || /[^0-9a-fA-F]/.test(clean)) {
    throw new Error(`field "${field}" is not valid hex`);
  }
  return Buffer.from(clean, "hex");
}

/** Constant-time-ish hex equality (length-checked first). */
function hexEq(a: string, b: string): boolean {
  const x = a.trim().toLowerCase();
  const y = b.trim().toLowerCase();
  if (x.length !== y.length) return false;
  let diff = 0;
  for (let i = 0; i < x.length; i++) diff |= x.charCodeAt(i) ^ y.charCodeAt(i);
  return diff === 0;
}

/**
 * Build a Node public key from raw big-endian RSA modulus + exponent by
 * importing them as a JWK (base64url, unsigned big-endian — RFC 7518).
 */
function rsaPublicKeyFromRaw(modulusBe: Buffer, exponentBe: Buffer) {
  const stripLeadingZeros = (b: Buffer): Buffer => {
    let i = 0;
    while (i < b.length - 1 && b[i] === 0) i++;
    return b.subarray(i);
  };
  const n = stripLeadingZeros(modulusBe).toString("base64url");
  const e = stripLeadingZeros(exponentBe).toString("base64url");
  return createPublicKey({ key: { kty: "RSA", n, e }, format: "jwk" });
}

/**
 * Verify a TEE attestation evidence blob.
 *
 * Pure function: performs no network or filesystem I/O. The caller is
 * responsible for sending a fresh random nonce and for sourcing the reference
 * measurement list / pinned key fingerprints (design doc §7.1).
 */
export function verifyAttestation(
  evidence: AttestationEvidence,
  opts: VerifyOptions,
): VerifyResult {
  const errors: string[] = [];
  const warnings: string[] = [];
  let signatureValid = false;
  let keyFingerprintHex = "";
  let measurementHex = "";

  try {
    const nonce = hexToBuf(evidence.nonce, "nonce");
    const measurement = hexToBuf(evidence.ta_measurement, "ta_measurement");
    const signature = hexToBuf(evidence.signature, "signature");
    const modulus = hexToBuf(evidence.attest_pubkey_mod, "attest_pubkey_mod");
    const exponent = hexToBuf(evidence.attest_pubkey_exp, "attest_pubkey_exp");
    measurementHex = measurement.toString("hex");

    if (measurement.length !== 32) {
      errors.push(`ta_measurement must be 32 bytes, got ${measurement.length}`);
    }

    // Key fingerprint = SHA-256 of the modulus (stable across exponent encoding).
    keyFingerprintHex = createHash("sha256").update(modulus).digest("hex");

    // 1. Nonce binding: echoed nonce must equal what we sent.
    if (!hexEq(evidence.nonce, opts.expectedNonceHex)) {
      errors.push("echoed nonce does not match the nonce that was sent (possible replay)");
    }

    // 2. Algorithm must be the one the PTA documents.
    if (evidence.sig_alg !== TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA256) {
      errors.push(
        `unexpected sig_alg 0x${evidence.sig_alg.toString(16)} ` +
          `(expected 0x${TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA256.toString(16)})`,
      );
    }

    // 3. Signature: RSA-PSS(SHA-256, salt 32) over SHA256(nonce || measurement).
    //    crypto.verify('sha256', M) computes SHA256(M) internally, so passing
    //    M = nonce||measurement reproduces the PTA's signed digest exactly.
    try {
      const key = rsaPublicKeyFromRaw(modulus, exponent);
      const signedMessage = Buffer.concat([nonce, measurement]);
      signatureValid = cryptoVerify(
        "sha256",
        signedMessage,
        { key, padding: constants.RSA_PKCS1_PSS_PADDING, saltLength: 32 },
        signature,
      );
      if (!signatureValid) errors.push("RSA-PSS attestation signature is INVALID");
    } catch (e) {
      errors.push(`signature verification threw: ${(e as Error).message}`);
    }

    // 4. Measurement allow-list (reference value, design doc §7.1).
    if (opts.expectedMeasurementsHex && opts.expectedMeasurementsHex.length > 0) {
      const match = opts.expectedMeasurementsHex.some((m) => hexEq(m, measurementHex));
      if (!match) {
        errors.push(
          `ta_measurement ${measurementHex} is not in the expected reference list ` +
            `(wrong/unknown TA build)`,
        );
      }
    } else {
      warnings.push(
        "no expectedMeasurementsHex provided — TA-identity check SKIPPED (unsafe in production)",
      );
    }

    // 5. TOFU key pinning.
    if (opts.pinnedKeyFingerprintsHex && opts.pinnedKeyFingerprintsHex.length > 0) {
      const pinned = opts.pinnedKeyFingerprintsHex.some((f) => hexEq(f, keyFingerprintHex));
      if (!pinned) {
        errors.push(
          `attestation key fingerprint ${keyFingerprintHex} is not pinned ` +
            `(untrusted device key — TOFU mismatch)`,
        );
      }
    } else {
      warnings.push(
        `no pinnedKeyFingerprintsHex provided — trust root NOT enforced. ` +
          `Pin this key on first use: ${keyFingerprintHex}`,
      );
    }
  } catch (e) {
    errors.push((e as Error).message);
  }

  return {
    ok: errors.length === 0,
    errors,
    warnings,
    keyFingerprintHex,
    measurementHex,
    signatureValid,
  };
}

/** 32 random bytes as a hex string — a convenient fresh nonce for a request. */
export function freshNonceHex(): string {
  // Lazy import keeps the module usable in environments that polyfill crypto.
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  return Buffer.from(globalThis.crypto.getRandomValues(new Uint8Array(32))).toString("hex");
}
