// Created: 2026-06-16
//
// RFC 6962 Merkle inclusion-proof verification — the universal mathematical core
// of every transparency log (Sigsum, Rekor, Certificate Transparency all use it).
// This is step one of issue #87 (B: measurement transparency log): given a leaf,
// its position, the tree size, and an audit path, reconstruct the Merkle root so
// the caller can compare it to a signed (and witness-cosigned) tree head.
//
// Zero runtime dependencies — node:crypto only — matching this package's
// deliberately lightweight, audit-friendly design (the whole verifier is
// reviewable without pulling a crypto supply chain).
//
// Algorithm is the canonical transparency-dev/merkle `RootFromInclusionProof`
// (decompose into inner + border nodes), the same one Sigsum and CT verifiers
// use. NOTE: the Sigsum-specific wire formats (leaf serialization with the
// submitter signature + key hash, the C2SP checkpoint note, witness cosignature
// encoding + witness policy) are intentionally NOT hand-rolled here — they will
// be implemented against the exact Sigsum protocol spec with REAL test vectors
// generated by sigsum-go, to avoid shipping subtly-wrong security crypto.

import { createHash, timingSafeEqual } from "node:crypto";

const HASH_SIZE = 32;

/** RFC 6962 leaf hash: SHA-256(0x00 || data). */
export function hashLeaf(data: Buffer): Buffer {
  return createHash("sha256").update(Buffer.from([0x00])).update(data).digest();
}

/** RFC 6962 interior node hash: SHA-256(0x01 || left || right). */
export function hashChildren(left: Buffer, right: Buffer): Buffer {
  return createHash("sha256")
    .update(Buffer.from([0x01]))
    .update(left)
    .update(right)
    .digest();
}

/** Number of significant bits in x (x >= 0); bitLength(0) === 0. */
function bitLength(x: bigint): number {
  let n = 0;
  while (x > 0n) {
    x >>= 1n;
    n++;
  }
  return n;
}

/** Population count (number of set bits) of x (x >= 0). */
function popcount(x: bigint): number {
  let n = 0;
  while (x > 0n) {
    n += Number(x & 1n);
    x >>= 1n;
  }
  return n;
}

export interface InclusionProofInput {
  /** Leaf hash (32 bytes) — e.g. hashLeaf(serializedLeaf). */
  leafHash: Buffer;
  /** 0-based index of the leaf within the tree. */
  index: bigint;
  /** Total number of leaves in the tree the root commits to. */
  treeSize: bigint;
  /** Audit path: ordered sibling hashes, each 32 bytes. */
  proof: Buffer[];
}

/**
 * Reconstruct the Merkle root from an inclusion proof (RFC 6962 /
 * transparency-dev `RootFromInclusionProof`). Throws on malformed input
 * (out-of-range index, wrong proof length, wrong hash size) so a caller can
 * never mistake a malformed proof for a non-matching root.
 */
export function rootFromInclusionProof(input: InclusionProofInput): Buffer {
  const { leafHash, index, treeSize, proof } = input;
  if (leafHash.length !== HASH_SIZE) {
    throw new Error("leafHash must be 32 bytes");
  }
  if (treeSize <= 0n) {
    throw new Error("treeSize must be positive");
  }
  if (index < 0n || index >= treeSize) {
    throw new Error("index out of range (require 0 <= index < treeSize)");
  }
  for (const h of proof) {
    if (h.length !== HASH_SIZE) throw new Error("each proof hash must be 32 bytes");
  }

  // Decompose the proof into `inner` nodes (mixed left/right by index bits) and
  // `border` nodes (always hashed on the right of the running result).
  const inner = bitLength(index ^ (treeSize - 1n));
  const border = popcount(index >> BigInt(inner));
  if (proof.length !== inner + border) {
    throw new Error(
      `malformed proof: expected ${inner + border} hashes (inner=${inner}, border=${border}), got ${proof.length}`,
    );
  }

  // chainInner: combine with siblings, side chosen by the i-th bit of index.
  let res = leafHash;
  for (let i = 0; i < inner; i++) {
    const h = proof[i];
    if (((index >> BigInt(i)) & 1n) === 0n) {
      res = hashChildren(res, h);
    } else {
      res = hashChildren(h, res);
    }
  }
  // chainBorderRight: remaining nodes are always the left sibling.
  for (let i = inner; i < proof.length; i++) {
    res = hashChildren(proof[i], res);
  }
  return res;
}

/**
 * Verify a leaf is included in a tree whose root is `expectedRoot`. Returns
 * false (never throws) on any malformed input or mismatch, so it is safe to use
 * directly as a gate.
 */
export function verifyInclusionProof(
  input: InclusionProofInput,
  expectedRoot: Buffer,
): boolean {
  let root: Buffer;
  try {
    root = rootFromInclusionProof(input);
  } catch {
    return false;
  }
  return root.length === expectedRoot.length && timingSafeEqual(root, expectedRoot);
}
