// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// WebAuthn PassKey assertion data — attached to sign/export/delete requests
/// for TA-level mandatory verification when a passkey is bound to the wallet.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct PasskeyAssertion {
    /// authenticatorData from WebAuthn assertion
    pub authenticator_data: Vec<u8>,
    /// SHA-256(clientDataJSON) - 32 bytes
    pub client_data_hash: [u8; 32],
    /// ECDSA signature r component (32 bytes)
    pub signature_r: [u8; 32],
    /// ECDSA signature s component (32 bytes)
    pub signature_s: [u8; 32],
    /// Raw clientDataJSON bytes (issue #49 — TA-side challenge binding / anti-replay).
    ///
    /// When present, the TA:
    ///   1. Verifies `SHA-256(client_data_json) == client_data_hash` so the JSON is
    ///      cryptographically bound to the ECDSA-signed message (a compromised CA
    ///      cannot lie about the JSON it forwards).
    ///   2. Extracts the `challenge` field, base64url-decodes it, and matches it
    ///      against the one-time nonce the TA itself issued via `GetChallenge`.
    ///
    /// `None` = legacy clients that predate #49. Handled per the TA's
    /// `ENFORCE_TA_CHALLENGE` policy (transition: allowed + warned; strict: rejected).
    /// `#[serde(default)]` keeps bincode wire-compatible with old hosts/TAs that
    /// never set this field.
    #[serde(default)]
    pub client_data_json: Option<Vec<u8>>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct CreateWalletInput {
    /// P-256 public key in uncompressed format (65 bytes: 0x04 || x || y)
    pub passkey_pubkey: Vec<u8>,
    /// Optional CA-provided entropy seed: 32 bytes wallet entropy + 16 bytes UUID seed (48 total).
    /// When present the TA uses this instead of TEE_GenerateRandom(), bypassing CAAM TRNG.
    /// Entropy is generated by the CA using Linux OsRng (/dev/urandom-backed CSPRNG).
    /// This is the fallback for boards where CAAM TRNG is unreliable or stuck.
    #[serde(default)]
    pub entropy_seed: Option<Vec<u8>>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct CreateWalletOutput {
    pub wallet_id: Uuid,
    pub mnemonic: String,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct RemoveWalletInput {
    pub wallet_id: Uuid,
    #[serde(default)]
    pub passkey_assertion: Option<PasskeyAssertion>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct RemoveWalletOutput {}

/// Admin force-delete: removes wallet from TEE secure storage without passkey verification.
/// Used exclusively for gap keys (passkey_pubkey bytes are not a valid P-256 curve point).
/// NOT called for normal wallets — requires the caller (api_server) to have already validated
/// that the key is a gap key before invoking.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct ForceRemoveWalletInput {
    pub wallet_id: Uuid,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct ForceRemoveWalletOutput {}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct DeriveAddressInput {
    pub wallet_id: Uuid,
    pub hd_path: String,
    #[serde(default)]
    pub passkey_assertion: Option<PasskeyAssertion>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct DeriveAddressOutput {
    pub address: [u8; 20],
    pub public_key: Vec<u8>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct EthTransaction {
    pub chain_id: u64,
    pub nonce: u128,
    pub to: Option<[u8; 20]>,
    pub value: u128,
    pub gas_price: u128,
    pub gas: u128,
    pub data: Vec<u8>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct SignTransactionInput {
    pub wallet_id: Uuid,
    pub hd_path: String,
    pub transaction: EthTransaction,
    #[serde(default)]
    pub passkey_assertion: Option<PasskeyAssertion>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct SignTransactionOutput {
    pub signature: Vec<u8>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct SignMessageInput {
    pub wallet_id: Uuid,
    pub hd_path: String,
    pub message: Vec<u8>,
    #[serde(default)]
    pub passkey_assertion: Option<PasskeyAssertion>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct SignMessageOutput {
    pub signature: Vec<u8>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct SignHashInput {
    pub wallet_id: Uuid,
    pub hd_path: String,
    pub hash: [u8; 32],
    #[serde(default)]
    pub passkey_assertion: Option<PasskeyAssertion>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct SignHashOutput {
    pub signature: Vec<u8>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct DeriveAddressAutoInput {
    pub wallet_id: Uuid,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct DeriveAddressAutoOutput {
    pub wallet_id: Uuid,
    pub address: [u8; 20],
    pub public_key: Vec<u8>,
    pub derivation_path: String,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct ExportPrivateKeyInput {
    pub wallet_id: Uuid,
    pub derivation_path: String,
    #[serde(default)]
    pub passkey_assertion: Option<PasskeyAssertion>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct ExportPrivateKeyOutput {
    pub private_key: Vec<u8>, // 32 bytes
}

/// WebAuthn PassKey (P-256/secp256r1) ECDSA verification
/// TA verifies the passkey signature before allowing private key operations
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct VerifyPasskeyInput {
    /// The wallet being accessed (for audit logging)
    pub wallet_id: Uuid,
    /// P-256 public key in uncompressed format (65 bytes: 0x04 || x || y)
    pub public_key: Vec<u8>,
    /// authenticatorData from WebAuthn assertion
    pub authenticator_data: Vec<u8>,
    /// SHA-256(clientDataJSON) - 32 bytes
    pub client_data_hash: [u8; 32],
    /// ECDSA signature r component (32 bytes)
    pub signature_r: [u8; 32],
    /// ECDSA signature s component (32 bytes)
    pub signature_s: [u8; 32],
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct VerifyPasskeyOutput {
    pub valid: bool,
}

/// Register a PassKey public key to a wallet (stored in TEE secure storage).
/// Once registered, all sensitive operations require PassKey assertion.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct RegisterPasskeyTaInput {
    pub wallet_id: Uuid,
    /// New P-256 public key in uncompressed format (65 bytes: 0x04 || x || y)
    pub passkey_pubkey: Vec<u8>,
    /// Current passkey assertion (required to change passkey)
    pub passkey_assertion: Option<PasskeyAssertion>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct RegisterPasskeyTaOutput {
    pub registered: bool,
}

/// Pre-load wallet into TA memory cache (no crypto, just storage read + seed cache).
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct WarmupCacheInput {
    pub wallet_id: Uuid,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct WarmupCacheOutput {
    pub cached: bool,
    pub cache_size: u32,
}

// Agent Key Commands

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct CreateAgentKeyInput {
    pub wallet_id: Uuid,
    pub agent_index: u32,
    /// JWT sub claim (typically the human key ID string).
    pub subject: String,
    /// JWT lifetime in seconds (TA enforces 1..=604800 cap).
    /// TA computes iat = now() internally; host does not supply iat.
    pub ttl_secs: i64,
    /// Passkey assertion — mandatory when wallet has a PassKey bound.
    /// TA verifies this before creating/refreshing agent credentials.
    #[serde(default)]
    pub passkey_assertion: Option<PasskeyAssertion>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct CreateAgentKeyOutput {
    pub agent_address: [u8; 20],
    pub public_key_compressed: Vec<u8>,
    /// JWT material for assembling the credential on the host side.
    /// wallet_id and agent_index in the payload are TEE-constructed (not host-supplied).
    pub jwt_kid: String,
    pub jwt_header_b64: String,
    pub jwt_payload_b64: String,
    pub jwt_hmac: [u8; 32],
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct SignAgentUserOpInput {
    pub wallet_id: Uuid,
    pub agent_index: u32,
    pub user_op_hash: [u8; 32],
    /// JWT authorization proof verified inside TEE (defense-in-depth against compromised CA).
    /// Fields extracted from the agent Bearer JWT by the host before calling TA.
    pub jwt_kid: String,
    pub jwt_signing_input: Vec<u8>, // b64url(header).b64url(payload) bytes
    pub jwt_hmac: Vec<u8>,          // 32 bytes — HMAC-SHA256 from JWT signature field
    /// Smart Account contract address that this session key is bound to.
    /// Embedded in the v0.17.2 signature wire format: [0x08][account(20)][key(20)][ECDSA(65)].
    /// Verified on-chain by SessionKeyValidator to prevent cross-account session-key abuse.
    pub account_address: [u8; 20],
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct SignAgentUserOpOutput {
    pub signature: Vec<u8>,
}

// JWT HMAC Commands

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct JwtHmacVerifyInput {
    pub kid: String,
    pub message: Vec<u8>,
    pub expected_hmac: Vec<u8>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct JwtHmacVerifyOutput {
    pub valid: bool,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct JwtRotateSecretInput {
    pub force: bool,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct JwtRotateSecretOutput {
    pub new_kid: String,
    pub retired_kid: Option<String>,
}

// EIP-712 Typed Data Signing

/// EIP-712 domain separator fields (all optional per spec)
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct Eip712Domain {
    pub name: Option<String>,
    pub version: Option<String>,
    pub chain_id: Option<u64>,
    pub verifying_contract: Option<[u8; 20]>,
}

/// A single field definition in an EIP-712 type
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct Eip712TypeField {
    pub name: String,
    pub field_type: String,
}

/// A named struct type with its field definitions
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct Eip712TypeDef {
    pub name: String,
    pub fields: Vec<Eip712TypeField>,
}

/// A typed value for EIP-712 message fields.
/// v0.18.1 scope: flat primitive types only (no array, no nested struct).
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub enum Eip712Value {
    Address([u8; 20]),
    /// Big-endian unsigned integer, 1–32 bytes (uint8 through uint256)
    Uint(Vec<u8>),
    Bytes32([u8; 32]),
    Bool(bool),
    Str(String),
    Bytes(Vec<u8>),
}

/// A named field-value pair in the EIP-712 message
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct Eip712FieldValue {
    pub name: String,
    pub value: Eip712Value,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct SignTypedDataInput {
    pub wallet_id: Uuid,
    pub hd_path: String,
    /// EIP-712 domain separator
    pub domain: Eip712Domain,
    /// Primary type name (the type being signed)
    pub primary_type: String,
    /// All type definitions referenced (primary type + any referenced types)
    pub types: Vec<Eip712TypeDef>,
    /// The message values for the primary type
    pub message: Vec<Eip712FieldValue>,
    /// Passkey assertion for WebAuthn path. TA verifies this independently.
    #[serde(default)]
    pub passkey_assertion: Option<PasskeyAssertion>,
    /// JWT proof fields for agent-key auth path (defense-in-depth: TA verifies HMAC independently).
    /// All three must be Some together; absent on WebAuthn path.
    #[serde(default)]
    pub jwt_kid: Option<String>,
    #[serde(default)]
    pub jwt_signing_input: Option<Vec<u8>>,
    #[serde(default)]
    pub jwt_hmac: Option<Vec<u8>>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct SignTypedDataOutput {
    /// 65 bytes: R(32) || S(32) || V(1), V normalized to 27/28
    pub signature: Vec<u8>,
}

// ── P256 Session Key (v0.18.1) ──
// Wire format: [0x08][account(20)][keyX(32)][keyY(32)][r(32)][s(32)] = 149 bytes

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct CreateP256SessionKeyInput {
    pub wallet_id: Uuid,
    pub session_index: u32,
    /// JWT sub claim (typically the human key ID string).
    pub subject: String,
    /// JWT lifetime in seconds (TA enforces 1..=604800 cap).
    pub ttl_secs: i64,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct CreateP256SessionKeyOutput {
    /// P-256 public key X coordinate (32 bytes big-endian)
    pub pub_key_x: [u8; 32],
    /// P-256 public key Y coordinate (32 bytes big-endian)
    pub pub_key_y: [u8; 32],
    /// JWT material for assembling the session credential on the host side.
    pub jwt_kid: String,
    pub jwt_header_b64: String,
    pub jwt_payload_b64: String,
    pub jwt_hmac: [u8; 32],
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct SignP256UserOpInput {
    pub wallet_id: Uuid,
    pub session_index: u32,
    pub user_op_hash: [u8; 32],
    /// JWT kid for TA-side HMAC authorization check (defense-in-depth)
    pub jwt_kid: String,
    pub jwt_signing_input: Vec<u8>,
    pub jwt_hmac: Vec<u8>,
    /// ERC-4337 Smart Account address embedded in wire format to prevent cross-account abuse
    pub account_address: [u8; 20],
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct SignP256UserOpOutput {
    /// 149 bytes: [0x08][account(20)][keyX(32)][keyY(32)][r(32)][s(32)]
    pub signature: Vec<u8>,
}

// Grant Session Signing — owner generates off-chain sig; relayer submits on-chain

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct SignGrantSessionInput {
    pub wallet_id: Uuid,
    pub hd_path: String,
    pub chain_id: u64,
    pub verifying_contract: [u8; 20],
    pub account: [u8; 20],
    pub session_key: [u8; 20],
    pub expiry: u64,
    pub contract_scope: [u8; 20],
    pub selector_scope: [u8; 4],
    pub velocity_limit: u16,
    pub velocity_window: u32,
    /// Raw address list — TA computes keccak256(abi.encodePacked(callTargets))
    pub call_targets: Vec<[u8; 20]>,
    /// Raw 4-byte selector list — TA computes keccak256(abi.encodePacked(selectorAllowlist))
    pub selector_allowlist: Vec<[u8; 4]>,
    /// Big-endian uint256 nonce from grantNonces[account][sessionKey] on-chain
    pub nonce: [u8; 32],
    #[serde(default)]
    pub passkey_assertion: Option<PasskeyAssertion>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct SignGrantSessionOutput {
    /// 65 bytes: R(32) || S(32) || V(1), V normalized to 27/28
    pub signature: Vec<u8>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct SignP256GrantSessionInput {
    pub wallet_id: Uuid,
    pub hd_path: String,
    pub chain_id: u64,
    pub verifying_contract: [u8; 20],
    pub account: [u8; 20],
    pub key_x: [u8; 32],
    pub key_y: [u8; 32],
    pub expiry: u64,
    pub contract_scope: [u8; 20],
    pub selector_scope: [u8; 4],
    pub velocity_limit: u16,
    pub velocity_window: u32,
    pub call_targets: Vec<[u8; 20]>,
    pub selector_allowlist: Vec<[u8; 4]>,
    /// Big-endian uint256 nonce from grantNonces_p256[account][keyHash] on-chain
    pub nonce: [u8; 32],
    #[serde(default)]
    pub passkey_assertion: Option<PasskeyAssertion>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct SignP256GrantSessionOutput {
    /// 65 bytes: R(32) || S(32) || V(1), V normalized to 27/28
    pub signature: Vec<u8>,
}

/// Delete a P256 session key from TEE secure storage (GC cleanup).
/// Called by the host's lazy GC on create/sign/revoke when the credential has expired.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct DeleteP256SessionKeyInput {
    pub wallet_id: Uuid,
    pub session_index: u32,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct DeleteP256SessionKeyOutput {
    /// true if the key existed and was deleted; false if it was already absent (idempotent).
    pub deleted: bool,
}

/// Read the current RPMB anti-rollback counter value (diagnostic).
/// No auth required — counter value is not sensitive.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct ReadRollbackCounterInput {}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct ReadRollbackCounterOutput {
    /// Current RPMB counter value. 0 = counter not yet initialized (no mutations recorded).
    pub counter: u64,
}

/// Request a fresh one-time WebAuthn challenge nonce from the TA (issue #49).
///
/// The TA generates 32 bytes via `optee_utee::Random`, stores `(wallet_id, nonce, issued_at)`
/// in an in-memory pending table, and returns the nonce. The host MUST use this nonce as the
/// WebAuthn `challenge` presented to the browser, so the value the authenticator signs is the
/// one the TA can later verify. The nonce is single-use and expires after `CHALLENGE_TTL_SECS`.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct GetChallengeInput {
    /// Wallet the challenge is bound to. A nonce issued for wallet A cannot be
    /// consumed by an assertion against wallet B.
    pub wallet_id: Uuid,
    /// Issue #68 — payload-bound challenge (closes V4: CA swaps payload).
    ///
    /// The 32-byte digest of the message the client intends to sign with the
    /// resulting assertion (e.g. the userOpHash, the SignHash hash, or the
    /// EIP-712 digest). The TA stores `(wallet_id, nonce, payload_digest)` and,
    /// at signing time, requires the ACTUAL payload being signed to hash to this
    /// value — so an assertion authorised for one payload cannot be redirected
    /// by a compromised CA to sign a different one.
    ///
    /// `None` = legacy / non-payload operations (handled per the TA's strict
    /// policy). NOTE: `#[serde(default)]` is honored by the self-describing
    /// serde_json API layer, but bincode is NOT self-describing and does NOT
    /// tolerate a missing trailing field across the host<->TA boundary — so
    /// cross-version safety relies on host+TA being deployed in lockstep from the
    /// same proto revision (they always are), NOT on serde(default). The
    /// attribute is retained for the JSON layer + ergonomic construction.
    #[serde(default)]
    pub payload_digest: Option<[u8; 32]>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct GetChallengeOutput {
    /// 32-byte one-time nonce. Host base64url-encodes this as the WebAuthn challenge.
    pub nonce: Vec<u8>,
}

/// Issue #37 — remote-attestation MVP request.
///
/// The caller (verifier / client) supplies a fresh random `nonce` to bind the
/// resulting evidence to this challenge and defeat replay. The OP-TEE
/// attestation PTA requires the nonce to be non-empty.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct GetAttestationInput {
    /// Fresh random challenge (non-empty). Echoed back in the output and bound
    /// into the signature as `SIG(SHA256(nonce | digest))`.
    pub nonce: Vec<u8>,
}

/// Issue #37 — remote-attestation MVP evidence.
///
/// Produced inside the TA by invoking the OP-TEE attestation PTA
/// (`39800861-182a-4720-9b67-2bcd622bc0b5`):
///  - `GET_TA_SHDR_DIGEST` (cmd 0x1) → `ta_measurement` (the TA signed-header
///    `shdr::hash`) and `signature` over `SHA256(nonce | ta_measurement)`,
///    using `TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA256` (salt length 32).
///  - `GET_PUBKEY` (cmd 0x0) → the attestation RSA public key
///    (`attest_pubkey_exp`, `attest_pubkey_mod`, big-endian) and `sig_alg`.
///
/// ⚠️ Trust-root scope (MVP): the attestation key is **self-generated by the
/// device's OP-TEE on first use** — it carries NO certificate chain to an NXP
/// root (confirmed against `core/pta/attestation.c` and RM00284 — see
/// `docs/design/37-remote-attestation-design.md` R-1). A verifier therefore
/// trusts this key via TOFU / a published reference value, NOT via an NXP root.
/// This proves "ran inside a real OP-TEE as this exact TA" but not "this is a
/// genuine NXP part the verifier never trusted before". Closing that gap is
/// Phase 2 (ELE anchoring), pending R-1.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct GetAttestationOutput {
    /// The nonce as echoed by the PTA (verifier MUST check it equals the one sent).
    pub nonce: Vec<u8>,
    /// 16-byte canonical (RFC 4122 big-endian) UUID of the measured TA — this TA.
    pub ta_uuid: Vec<u8>,
    /// 32-byte digest from the TA signed header (`struct shdr::hash`). Verifier
    /// compares this against the published `kms_ta_measurement` reference value.
    pub ta_measurement: Vec<u8>,
    /// RSA-PSS signature over `SHA256(nonce | ta_measurement)`. Length equals the
    /// attestation key modulus length (e.g. 256 B for RSA-2048, 384 B for 3072).
    pub signature: Vec<u8>,
    /// Attestation RSA public key exponent, big-endian (from GET_PUBKEY memref[0]).
    pub attest_pubkey_exp: Vec<u8>,
    /// Attestation RSA public key modulus, big-endian (from GET_PUBKEY memref[1]).
    pub attest_pubkey_mod: Vec<u8>,
    /// Signature algorithm id reported by GET_PUBKEY value[2]
    /// (currently always `TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA256` = 0x70414930).
    pub sig_alg: u32,
    /// REE wall-clock seconds at evidence generation (`optee_utee::Time::ree_time`).
    /// Informational only — REE time is untrusted; freshness is enforced by `nonce`.
    pub ree_time_secs: u64,
}
