[build]
target = "aarch64-unknown-optee"
target-dir = "target"

[target.aarch64-unknown-optee]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-C", "link-arg=-Wl,--allow-multiple-definition"]

[env]
RUST_TARGET_PATH = { value = "/opt/teaclave/std", force = true }
