[package]
name = "airaccount-ca-test"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.8", features = ["v4", "serde"] }
anyhow = "1.0"
hex = "0.4"
clap = { version = "4.0", features = ["derive"] }
webauthn-rs = { version = "0.5", features = ["danger-allow-state-serialisation"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.5"
base64 = "0.22"
thiserror = "1.0"