package main

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"

	"sigsum.org/sigsum-go/pkg/crypto"
	"sigsum.org/sigsum-go/pkg/types"
)

func seedSigner(b byte) (crypto.PublicKey, *crypto.Ed25519Signer) {
	var s crypto.PrivateKey
	for i := range s {
		s[i] = b
	}
	sg := crypto.NewEd25519Signer(&s)
	return sg.Public(), sg
}
func h(b []byte) string { return hex.EncodeToString(b) }

func kh(p crypto.PublicKey) string { hh := crypto.HashBytes(p[:]); return h(hh[:]) }
func cosigs(w1 crypto.PublicKey, ts uint64, c1 types.Cosignature, w2 crypto.PublicKey, c2 types.Cosignature) []map[string]any {
	return []map[string]any{
		{"keyHash": kh(w1), "timestamp": ts, "signature": h(c1.Signature[:])},
		{"keyHash": kh(w2), "timestamp": ts, "signature": h(c2.Signature[:])},
	}
}
func main() {
	subPub, subSig := seedSigner(0x11)
	logPub, logSig := seedSigner(0x22)
	w1Pub, w1Sig := seedSigner(0x33)
	w2Pub, w2Sig := seedSigner(0x44)

	data := []byte("airaccount attestation-measurements manifest (test vector)")
	msg := crypto.HashBytes(data)            // what proof.Verify takes as msg
	checksum := crypto.HashBytes(msg[:])     // leaf checksum
	sig, _ := types.SignLeafChecksum(subSig, &checksum)
	leaf := types.Leaf{Checksum: checksum, Signature: sig, KeyHash: crypto.HashBytes(subPub[:])}
	if !leaf.Verify(&subPub) {
		fmt.Fprintln(os.Stderr, "self-check: leaf verify failed"); os.Exit(1)
	}
	leafHash := leaf.ToHash() // size=1 tree root == leaf hash

	th := types.TreeHead{Size: 1, RootHash: leafHash}
	sth, _ := th.Sign(logSig)
	origin := types.SigsumCheckpointOrigin(&logPub)
	if !sth.Verify(&logPub) { fmt.Fprintln(os.Stderr, "sth verify failed"); os.Exit(1) }

	const ts = uint64(1750000000)
	cs1, _ := th.Cosign(w1Sig, origin, ts)
	cs2, _ := th.Cosign(w2Sig, origin, ts)
	if !cs1.Verify(&w1Pub, origin, &th) || !cs2.Verify(&w2Pub, origin, &th) {
		fmt.Fprintln(os.Stderr, "cosig verify failed"); os.Exit(1)
	}

	out := map[string]any{
		"_note":          "Generated by sigsum-go (authoritative). size=1 tree; root==leafHash.",
		"submitterKey":   h(subPub[:]),
		"logKey":         h(logPub[:]),
		"witnessKeys":    []string{h(w1Pub[:]), h(w2Pub[:])},
		"msg":            h(msg[:]),          // verifier input; checksum = SHA256(msg)
		"origin":         origin,
		"leaf":           map[string]string{"checksum": h(checksum[:]), "signature": h(sig[:]), "keyHash": h(leaf.KeyHash[:])},
		"leafHashHex":    h(leafHash[:]),
		"sth":            map[string]any{"size": th.Size, "rootHash": h(th.RootHash[:]), "signature": h(sth.Signature[:])},
		"checkpointBody": th.FormatCheckpoint(origin),
		"cosignatures": cosigs(w1Pub, ts, cs1, w2Pub, cs2),
	}
	b, _ := json.MarshalIndent(out, "", "  ")
	fmt.Println(string(b))
}
