[package]
name = "airaccount-core-logic"
version = "0.1.0"
edition = "2021"
authors = ["AirAccount Team"]
description = "Hardware-agnostic core logic for AirAccount TEE-based Web3 wallet"
license = "MIT"
repository = "https://github.com/aastar/AirAccount"

[dependencies]
# Cryptographic dependencies
aes-gcm = "0.10"
subtle = "2.5"
rand = "0.8"
rand_chacha = "0.3"

# eth_wallet integration dependencies
bip32 = { version = "0.3.0", features = ["bip39"] }
secp256k1 = "0.27.0"
ethereum-tx-sign = "6.1.3"
sha3 = "0.10.6"
uuid = { version = "1.8", default-features = false, features = ["v4", "serde"] }
bincode = "1.3.3"
hex = { version = "0.4", features = ["serde"] }
anyhow = "1.0"

# Enum utilities
num_enum = "0.7"

# Async support
async-trait = "0.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Memory safety
zeroize = { version = "1.7", features = ["derive"] }

# Error handling
thiserror = "1.0"

# Async runtime (optional, for future use)
tokio = { version = "1.0", features = ["rt", "sync"], optional = true }

# Logging
log = "0.4"

[dev-dependencies]
tokio-test = "0.4"
tokio = { version = "1.0", features = ["rt", "sync", "macros"] }

[features]
default = ["std"]
std = []
async = ["tokio"]
no-std = []

[lib]
name = "airaccount_core_logic"
path = "src/lib.rs"

[[bin]]
name = "security-test"
path = "src/bin/security_test.rs"